linux-x86_64-binaries_task:
  container:
    image: ubuntu:latest

  package_script:
    - apt-get update
    - touch higan-nightly.zip

  matrix:
    - only_if: $CIRRUS_RELEASE != ""
      environment:
        GITHUB_TOKEN: ENCRYPTED[d033af6698c514188fb259d9dd1e8ad79d903f017b57543a5f34cfeead1eec1037fb411e53a408a3bdff9f6d175fda8b]
      upload_script: ./.cirrus.upload.sh
    - only_if: $CIRRUS_RELEASE == ""

  higan-nightly_artifacts:
    path: "higan-nightly.zip"
